# Generated by Django 5.1.1 on 2024-09-26 16:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_criminalrecord_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('matched_image', models.ImageField(upload_to='matched_images/')),
                ('criminal_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.criminalrecord')),
            ],
        ),
    ]
