# Generated by Django 5.1.1 on 2024-09-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_matchrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalrecord',
            name='status',
            field=models.CharField(choices=[('WANTED', 'Wanted'), ('ON_BAIL', 'On Bail'), ('SERVING_SENTENCE', 'Serving Sentence'), ('COMPLETED_SENTENCE', 'Completed Sentence')], default='WANTED', max_length=50),
        ),
    ]
