# Generated by Django 5.1.1 on 2024-09-29 05:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_criminalrecord_prison_of_escape'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalrecord',
            name='arrest_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
